spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/ecobici-bd
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        type_contributor: com.demo.UserApi.models.PersonDtoTypeContributor
    show-sql: true

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

transporte:
  api:
    url: https://apitransporte.buenosaires.gob.ar/ecobici/gbfs

ecobici:
  auth:
    clientId: 99512ce528fa4346a461204d35deb6f6
    clientSecret: 4441C00135Eb4659B2687bfFd89D2e55
