server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/tabbirossi96/transporte-publico.git
          search-paths: config-data
  application:
    name: config-service
  output:
    ansi:
      enabled: ALWAYS

